### ISSUE TITLE
Question: smoke originating at bottom of full document height?

### ISSUE THREAD

**Issue by boldc** [bijection/smoke.js#3]
Hi, I love this smoke effect, thank you for making it available on github!!!

Is it possible to place an emitter on the bottom of the page, if the page height is greater than the viewport height (i.e., 'below the fold')?  Could you post an example of how this could be done?  I've tried a few things, but my nascent javascript skills have been unsuccessful.

Thanks again!

**Comment by bijection** [comment]
You can place the emitter anywhere on your canvas element - here's an example with a tall canvas element:

```html
<canvas id="canvas"></canvas>
<script src="smoke.js"></script>
<script>
    var canvas = document.getElementById('canvas')
    var ctx = canvas.getContext('2d')
    canvas.width = 1000
    canvas.height = 4000

    var party = smokemachine(ctx)

    party.start()

    party.addsmoke(500,3500,10) 

</script>
```
