### ISSUE TITLE
Safari?

### ISSUE THREAD

**Issue by controversial** [bijection/smoke.js#4]
This seems to work in Chrome but not safari, however no errors are raised, the script fails silently 😕

**Comment by bijection** [comment]
What version of safari and OSX are you using?

**Comment by bijection** [comment]
Never mind, it was broken on all versions of safari. Should be fixed now!

**Comment by controversial** [comment]
Wow, that was fast, thanks! What was the fix? Does Safari just not support base64 PNG rendering on canvas?

**Comment by bijection** [comment]
I'm not exactly sure, but the first getimagedata, which was supposed to extract the opacities for the smoke sprite, was returning completely zero. It may be that safari doesn't load base64 encoded srcs synchronously.

**Comment by controversial** [comment]
Ah, that sounds likely. Thanks!

**Comment by bijection** [comment]
Either way it's a more sane implementation now anyways 😀
